---
title: "DATA 605 Discussion Week 11 (12)"
subtitle: 'CUNY Spring 2021'
author: "Philip Tanofsky" 
date: "`r format(Sys.time(), '%d %B %Y')`"
header-includes:
   - \usepackage{amsmath}
output: pdf_document
---

```{r warning=F, message=F}
library(tidyverse)
library(stats)
library(broom)
library(ggplot2)
```


```{r warning=F, message=F, eval=F}
nba_data <- read_csv("https://raw.githubusercontent.com/fivethirtyeight/nba-player-advanced-metrics/master/nba-data-historical.csv")

nba_data <- nba_data %>% filter(year_id >= 2016) %>% select( 'P/36',  'A/36', 'R/36', 'Raptor O')

nba_data <- rename_with(nba_data, ~ gsub(" ", "_", .x, fixed = TRUE))
nba_data <- rename_with(nba_data, ~ gsub("/", "_", .x, fixed = TRUE))

nba_data$P_36 <- as.numeric(nba_data$P_36)
nba_data$A_36 <- as.numeric(nba_data$A_36)
nba_data$R_36 <- as.numeric(nba_data$R_36)

nba_data <- na.omit(nba_data)

nba_data <- nba_data %>% filter(P_36 <= 50)

dim(nba_data)

summary(nba_data)

plot(x = nba_data$P_36, y = nba_data$Raptor_O, main = "Raptor Offensive Rating by Points per 36")

plot(x = nba_data$A_36, y = nba_data$Raptor_O, main = "Raptor Offensive Rating by Assists per 36")

plot(x = nba_data$R_36, y = nba_data$Raptor_O, main = "Raptor Offensive Rating by Rebounds per 36")

model <- lm(Raptor_O ~ ., data=nba_data)
#model

summary(model)

model.diag.metrics <- augment(model)
head(model.diag.metrics)

#autoplot(model)
```

```{r warning=F, message=F, eval=F}
library(nbastatR)

#players_2019 <- teams_players_stats(seasons = 2019, types=player, return_message = T)

players_2018 <- teams_players_stats(seasons = 2018,
                    types = c("player", "team"),
                    modes = c("PerGame", "Totals"),
                    tables = c("general", "defense", "clutch", "hustle", "shots", "shot locations")
                   )

dim(players_2018)

summary(players_2018)
```

```{r warning=F, message=F}
library(NBAloveR)

bos <- getTeamHistory(team_code = "bos")
lal <- getTeamHistory(team_code = "lal")
chi <- getTeamHistory(team_code = "chi")
sas <- getTeamHistory(team_code = "sas")
phi <- getTeamHistory(team_code = "phi")

nba <- rbind(bos, lal)
nba <- rbind(nba, chi)
nba <- rbind(nba, sas)
nba <- rbind(nba, phi)

nba$RtgDif <- nba$ORtg - nba$DRtg

head(nba)

nba %>%
  ggplot(aes(x=ORtg, y=W)) + 
  geom_point() + 
  labs(title = 'Offensive Rating vs Wins') + geom_smooth(method='lm', formula= y~x)

nba %>%
  ggplot(aes(x=DRtg, y=W)) + 
  geom_point() + 
  labs(title = 'Defensive Rating vs Wins') + geom_smooth(method='lm', formula= y~x)

nba %>%
  ggplot(aes(x=RtgDif, y=W)) + 
  geom_point() + 
  labs(title = 'Rating vs Wins') + geom_smooth(method='lm', formula= y~x)

corr <- cor(nba$RtgDif, nba$W, use = "complete.obs")
corr

dim(nba)
summary(nba)


model_ortg <- lm(W ~ ORtg, data=nba)
summary(model_ortg)
model_drtg <- lm(W ~ DRtg, data=nba)
summary(model_drtg)
model_rtgdif <- lm(W ~ RtgDif, data=nba)
summary(model_rtgdif)
```


